#! /bin/bash
#
# /etc/init.d/MICE-rid_4_countermeasure
#
### BEGIN INIT INFO
# Provides:       MICE-rid_4_countermeasure
# Required-Start: $network MICE-bufferdaemon-mngmthost
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Description:    M-ICE: Starts ReactionProcess for Management Host
### END INIT INFO

. /etc/rc.status
#. /etc/rc.config

return=$rc_done
case "$1" in
    start)
	echo -n "M-ICE IDS: Starting Reaction Service 'rid_4_countermeasure'"
	startproc /usr/sbin/rid_4_countermeasure || return=$rc_failed
	echo -e "$return"
	;;
    stop)
	echo -n "M-ICE IDS: Stopping Reaction Service 'rid_4_countermeasure'"
	killproc /usr/sbin/rid_4_countermeasure || return=$rc_failed
	echo -e "$return"
	;;
    restart)
	$0 stop && $0 start
	;;
    status)
	echo "M-ICE IDS: Status Reaction Service 'rid_4_countermeasure':"
	checkproc -v /usr/sbin/rid_4_countermeasure || return=$rc_failed
        echo -e "$return"
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac
test "$return" = "$rc_done" || exit 1
exit 0

